### ISSUE TITLE
Rate of decline calculations

### ISSUE THREAD

**Issue by ajsmit** [robwschlegel/heatwaveR#1]
There is an error in the detect() function, which Eric fixed long ago in his python code. See the details in _testing/rate_of_decline_calcs.R. After this is done we need to compare results with that produced by the python code.

**Comment by ajsmit** [comment]
This is something that was fixed on 15 June 2017 in the R version; please make sure that edits made then result in the same outcomes as that produced by Eric's code edits.

**Comment by robwschlegel** [comment]
This has been checked out and everything matches up.
