### ISSUE TITLE
error with OISST vignette

### ISSUE THREAD

**Issue by glacierbliss** [robwschlegel/heatwaveR#10]
Hello,

I'm trying to run the vignette:
https://cran.r-project.org/web/packages/heatwaveR/vignettes/OISST_preparation.html
but get the following error:
 Error: Query error: For variable=sst axis#0=time Constraint="[(1982-01-01):1:(1989-12-31)]": Start="1982-01-01" is less than the axis minimum=2020-04-26T12:00:00Z (and even 2019-10-25T17:09:36Z).type Status reportmessage Your query produced no matching results. Query error: For variable=sst axis#0=time Constraint="[(1982-01-01):1:(1989-12-31)]": Start="1982-01-01" is less than the axis minimum=2020-04-26T12:00:00Z (and even 2019-10-25T17:09:36Z).description The server encountered an internal error that prevented it from fulfilling this request.Apache Tomcat/8.0.38 

As a relatively new R user, I'm not sure if this is something I'm doing wrong or if it is related to the new version 2.1 mentioned here:
https://www.ncdc.noaa.gov/oisst
I did my best to follow the vignette, including installing rerddap from GitHub.

Thanks for your work creating and sharing this code.

**Comment by robwschlegel** [comment]
Hello,
The ERDDAP server on which these NOAA OISST data are hosted very frequently has issues in service. They can last from hour to months. I've never been able to get an answer for why this is. If you follow this [link](https://www.ncei.noaa.gov/erddap/griddap/ncdc_oisst_v2_avhrr_by_time_zlev_lat_lon.html) you'll see that currently there is only one day of NOAA OISST data available on the server, 2020-04-26. That is why you are receiving your error.
After struggling with these issues for months I eventually stopped trying to access data from that server. Now that a new version has been released I don't foresee these intermittent issues becoming any less frequent. I now download the satellite data directly from a different, more stable server. Here is a blog post I wrote about how to do that: https://theoceancode.netlify.app/post/dl_env_data_r/
All the best,
-Robert

**Comment by robwschlegel** [comment]
Hello,
I've noticed now that the link to the blogpost I sent through was aimed at the old v2 data. I've updated it to now function with the v2.1 data.
I'll update the vignette that is on CRAN as well. But that will take several days for the normal CRAN upload process to run its course.
All the best,
-Robert
