### ISSUE TITLE
heat wave for land

### ISSUE THREAD

**Issue by fipoucat** [robwschlegel/heatwaveR#11]
More question than issue
I was looking for something similar for land and wonder if someone did this and/or adapted your package for land areas?

Thanks

**Comment by robwschlegel** [comment]
There is this vignette that shows the use of this package with air data (Tmin + Tmax): https://robwschlegel.github.io/heatwaveR/articles/complex_clims.html
This package was made so that it could be used with either air or sea data. I don't know what the atmospheric heatwave people use though as we are not in regular communication.

**Comment by fipoucat** [comment]
Thank you, I'll try to follow this example with Algiers with single station or points.

For spatial, I have a question related to doParallel when using a spatial large file of max temperaturein netcdf I have to convert as data frame with below loops taking days.  
Below my loop:
for (i in 1:length(date)) {
  
  ps = tibble(lon,tmx[,,i] %>% as_tibble())%>% 
    as_tibble() %>% 
    gather(key = "key", value = "tmx", 2:106) %>% 
    mutate(time = date[i], lat = rep(lat, each = 185)) %>% select(time, lon,lat, tmx)
  
  tmx.df = tmx.df %>% bind_rows(ps)
  
}
save(tmx.df,file="tmx.Rda")

How can I use doParallel in the above loop in an 8 cores machine?

Hope someone in this list could help?
Thank you

**Comment by robwschlegel** [comment]
Hello,
I've never seen someone extract data from a NetCDF file like that before so can't help much with the theory behind your approach. I would ask why you are not using a simple NetCDF data extraction package? tidync is my personal favourite: https://docs.ropensci.org/tidync/
Extracting data from NetCDF files is generally a very quick process so shouldn't need to be multicored. In most cases that will just slow the process down as the machine needs to allocate jobs to individual cores and then stitch the results back together.
Cheers

**Comment by fipoucat** [comment]
Hello Robert,

I agree with you because I think it should be easier. The sample code I showed is based on ncdf4, works for small domain or coarse resolution. In my case the domain is a little bit large with higher resolution.

I am not familiar with tidync, but will look at closely for the purpose. What I want at the end is just a data frame with the structure below using a small domain and a spatial resolution of 2.5x2.5 for a pameter slp:

   time                            lon      lat    slp
   <dttm>                <dbl>     <dbl>    <dbl>
 1 1978-12-30 12:00:00   0      40  1 015.
 2 1978-12-30 12:00:00   2.5    40  1013.
 3 1978-12-30 12:00:00   5      40   1012.
 4 1978-12-30 12:00:00   7.5    40   1010.
 5 1978-12-30 12:00:00  10      40   1007.
 6 1978-12-30 12:00:00  12.5    40   1005.
 7 1978-12-30 12:00:00  15      40   1004.
 8 1978-12-30 12:00:00  17.5    40   1003.
 9 1978-12-30 12:00:00  20      40   1002.
10 1978-12-30 12:00:00  22.5    40  1001. 

Best regards

**Comment by robwschlegel** [comment]
tidync is great because you point it at a NetCDF files and tell it to extract the data and it outputs it directly into the data frame format that you would want for your further analyses.

**Comment by fipoucat** [comment]
I am facing problem with my case slightly different because I have to extract temperature or other parameter at each grid point for all the time steps in the the netcdf file. I'll keep trying hope success quickly
