### ISSUE TITLE
event_line only plotting first event

### ISSUE THREAD

**Issue by boshek** [robwschlegel/heatwaveR#12]
Thank you for this wonderful package. It has a really nice API and clear instructions. I have found what I think if maybe an issue in the `event_line` function. From the documentation of that function:

> make sure start_date and end_date straddle this event, or simply leave them both as NULL (default) and event_line will use the entire time series date range.

If however I leave the `start_date` and `end_date` arguments NULL it appears as though only the first heatwave in the time series is plotted:

``` r
library(heatwaveR)
library(ggplot2)

ts <- ts2clm(sst_WA, climatologyPeriod = c("1983-01-01", "2012-12-31"))
res <- detect_event(ts)

event_line(res, spread = 100, metric = "intensity_cumulative")
```

![](https://i.imgur.com/yu0zH02.png)

I was expecting something a little more like this in which all heatwaves were plotted:

``` r
ggplot(data = res$climatology, aes(x = t, y = temp)) +
  geom_line(aes(y = seas, col = "Climatology"),
    size = 0.7, alpha = 1
  ) +
  geom_line(aes(y = seas, col = "Climatology"),
    size = 0.7, alpha = 1
  ) +
  geom_line(aes(y = thresh, col = "Threshold"),
    size = 0.7, alpha = 1
  ) +
  geom_line(aes(y = temp, col = "Temperature"), size = 0.6) +
  geom_flame(data = res$climatology, aes(y2 = thresh))
```

![](https://i.imgur.com/SdM2Cd1.png)

I think this is resulting from this line:
https://github.com/robwschlegel/heatwaveR/blob/d82b56ed87e35f169a822c02a5b4f05ed7d75229/R/graph_functions.R#L133

Is this a bug or is the intended behaviour that only the first event is plotted?

**Comment by robwschlegel** [comment]
Hello boshek,
Thank you for your observation. The issue you've posted isn't exactly the intended behaviour of this function, but I wouldn't say it's a bug either. The idea behind this function is to allow a user to quickly and easily plot a _single_ event based on the start date of the event. The idea being that a researcher likely has a focal event that they would like to visualise, and not to just show the full time series, which doesn't work well. I wrote this function a long time ago with the main purpose of matching the style of events in the [Hobday et al. (2016)](https://doi.org/10.1016/j.pocean.2015.12.014) publication from which this package originates. Were one to want to do something more involved with the marine heatwaves results one would need to write out the full **`ggplot2`** code themselves, as you did in your second example. That being said, if you do want to use the `event_line` function to plot multiple years of data, you can adjust the `spread` and `start_date` arguments accordingly. An example is given below.

``` r
library(heatwaveR)
library(ggplot2)

ts <- ts2clm(sst_WA, climatologyPeriod = c("1983-01-01", "2012-12-31"))
res <- detect_event(ts)

event_line(res, start_date = "2000-01-01", spread = 2000, metric = "intensity_cumulative")
```

![](https://i.imgur.com/0IVyEll.png)

<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

All the best,
-Robert
