### ISSUE TITLE
Fail gracefully if x or y are not as expected in detect_event

### ISSUE THREAD

**Issue by jebyrnes** [robwschlegel/heatwaveR#15]
Currently, if x or y is not defined in detect_event and they are other than the pre-specified variable names, when the user gets to the point of a new data frame creation, the function fails with a hard to interpret message, requiring the user (i.e., me) to debug(detect_event) and go through until they realize what the problem is.

I know, RTFM and all that, but, if there was a more graceful failure message when ts_x or ts_y gets evaluated to something other than a vector, it might help users quite a bit.

**Comment by robwschlegel** [comment]
Hello Jarrett,
I see your point. No one has ever brought this up before though so I don't think it is a relatively common issue. One will have needed to go about changing the column names from the output of ts2clm() during the analysis process to encounter this issue So I would argue it is up to the user to keep track of the changes they have made themselves. The function can't be written to account for every possible error.

But I did look into adding better error trapping to the source code to help improve the usability. Unfortunately the combo of eval() and substitute() used in the column selection process makes error trapping that step a black box. Therefore I am not going to be adding catches to those steps. For what it is worth, any relatively recent version of RStudio will tell you on exactly which line of code the function failed, and one may pull up the source code of any function by typing it's name into the console without the () afterwards. e.g. entering    detect_event   in the console will show the source code for it.
All the best,
-Robert

**Comment by robwschlegel** [comment]
Hello,
I wasn't happy with my previous answer, but you caught me in a time crunch last night and I wasn't able to look into the  issue as much as I would have liked. I went back to the problem this morning and sorted it out.
Please try out the new version of heatwaveR (v4.5.9001) by installing it from GitHub `remotes::install_github("robwschlegel/heatwaveR")`  . There should now be more useful errors returned when the function can't find the column names it needs. I added this error trapping to `ts2clm()`, `detect_event()`, and `exceedance()`.
All the best,
-Robert

**Comment by jebyrnes** [comment]
Thanks!
