### ISSUE TITLE
ts2clm function gives Error in seq.int(0, to0 - from, by) : 'to' must be a finite number

### ISSUE THREAD

**Issue by SaswatD** [robwschlegel/heatwaveR#16]
tdf <- read.csv('st_42369.csv',header=TRUE, stringsAsFactors = FALSE , na.strings = "NA")
tdf$t <- with(tdf,paste(YEAR,MN,DT,sep="-"))
tdf$t <- as.Date(tdf$t,format="%Y-%m-%d")

tdata <- subset(tdf,select= -c(YEAR,MN,DT,R.F))
tdata <- relocate(tdata,t,.before=MAX)
tdata$MAX <- as.numeric(tdata$MAX)
tMax_clim <- ts2clm(data = tdata, x = t , y = tdata$MAX, 
                    climatologyPeriod = c("1980-01-01", "2010-12-31"),
                    smoothPercentile = TRUE,smoothPercentileWidth = 31,
                    pctile = 90)

Error is coming : 

Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
Why does this error come?
Is it due to missing dates or what?

**Comment by robwschlegel** [comment]
Hello,
One is not meant to provide both the dataframe and column to the `y` argument. Try this instead:
`tMax_clim <- ts2clm(data = tdata, x = t , y = MAX, climatologyPeriod = c("1980-01-01", "2010-12-31")`
Cheers,
-Robert
