### ISSUE TITLE
flag heatwave in the data

### ISSUE THREAD

**Issue by Fred-Wu** [robwschlegel/heatwaveR#19]
Hi Robert, 
This is a general question regarding defining heatwave in the data. 

Since you are the package author on heatwave,  may I ask you opinion on this?

The usual heatwave definition in the health literature, for example, is

"a heat wave is defined as a period of at least 4 consecutive days with mean temperatures above the threshold of the 97th percentile of year-round daily mean temperature",  

As I understand, the days in the data should be flagged as heatwave are the periods with 4 or more days above a threshold, starting from the first day meeting the criteria. That's the purpose why I use  `exceedance` function in the previous thread.  

However, I also came across  a study done earlier, which only flags heatwave starting from the 4th day and onward when the previous 3 days meet the criteria. 

So in the first case, the flag is 
```
1, 1, 1, 1, 1, 0, 0, 0
```
And in the second, it is            
```
0, 0, 0, 1, 1, 0, 0, 0
``` 

I am new to climate study, so not quite sure which way should be used typically or whether they would result in different conclusions. 
It would be much appreciated if you could provide some advice. 

Thanks 
Fred

**Comment by robwschlegel** [comment]
Hello Fred,
I imagine that the two different methods of classifying the duration of heatwaves could lead to different conclusions, even though the general concept remains the same. But it is unlikely. The heatwaves that we had in mind when we wrote this package were those occurring in the natural world that would have some sort of ecological impact. So I can't speak to what the prevailing philosophy is in medical science, but in environmental science the standard way of defining these events is as you suspected: the duration of the event is from the first day when temperatures exceed the pre-determined threshold to the last day before temperatures go back below it. I've never before read a (environmental) paper where a heatwave required a certain number of days after exceeding a threshold before anyone began to count the days. That sounds more like a criteria that would have been developed to better indicate risk of heat exposure to humans. From a programming point of view I suppose one just needs to subtract three days from the length of a heatwave to accomplish the same thing. But then why bother with the extra step?
I hope that brief discussion helps.
-Robert

**Comment by Fred-Wu** [comment]
Thanks for your insights Robert.

> That sounds more like a criteria that would have been developed to better indicate risk of heat exposure to humans. 

I think this makes sense to me if considering the second coding scheme as heatwave exposure rather than heatwave event. Is this a correct interpretation or way of thinking?

I will see whether two coding schemes will lead to different conclusions or estimates in my own analysis.

**Comment by robwschlegel** [comment]
It sounds correct to me.
