### ISSUE TITLE
elapsed time of oisst vignette

### ISSUE THREAD

**Issue by chrisdane** [robwschlegel/heatwaveR#21]
Hi

I try to reproduce your [OISST preparation vignette](https://robwschlegel.github.io/heatwaveR/articles/OISST_preparation.html) and obtain dramatically different downloading times.

To have a clean session, I first run 
```r
library(rerddap)
cache_delete_all() # careful, deletes all your possibly cached ERDDAP data; see cache_info() 
```
Then run the code copy-pasted from the vignette:
```r
library(dplyr)

OISST_sub_dl <- function(time_df){
OISST_dat <- griddap(x = "ncdcOisst21Agg_LonPM180", 
                           url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
                           time = c(time_df$start, time_df$end), 
                           zlev = c(0, 0),
                           latitude = c(-40, -35),
                           #latitude = c(-89.875, -89.875), 
                           longitude = c(15, 21),
                           #longitude = c(-179.875, -179.875),
                           fields = "sst")$data %>% 
        mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z"))) %>% 
        dplyr::rename(t = time, temp = sst) %>% 
        select(lon, lat, t, temp) %>% 
        na.omit() 
}

dl_years <- data.frame(date_index = 1:5,
                       start = as.Date(c("1982-01-01", "1990-01-01", 
                                         "1998-01-01", "2006-01-01", "2014-01-01")),
                       end = as.Date(c("1989-12-31", "1997-12-31", 
                                       "2005-12-31", "2013-12-31", "2019-12-31")))

system.time(
        OISST_data <- dl_years %>% 
            group_by(date_index) %>% 
            group_modify(~OISST_sub_dl(.x)) %>% 
            ungroup() %>% 
            select(lon, lat, t, temp)
) 
```

In your vignette, you state that the above command needs

> 38 seconds, ~8 seconds per batch

For me, in contrast, it takes around 8 minutes. This long time does not reduce if I download only data from a specific lon,lat point, as indicated by the commented lines in the `griddap`-call. Am I doing something wrong?

Thanks for any help and cheers,
Chris

**Comment by robwschlegel** [comment]
Hello Chris,

Thank you for your query.

The code in this vignette (and it's speed) rely on several packages and servers that I do not have any affiliation with. The code provided here is meant to be a useful jumping off point for environmental scientists. I cannot ensure that the speeds that I posted years ago when this was written will remain the same.

I've run the code again myself now and it also took about 8 minutes. So it does not appear that you are doing anything wrong. Rather I assume that the NOAA servers are now slower in providing subsetted data via the ERDAAP system. I know that a lot of large US science serving systems are currently undergoing changes, so this could be again slower or perhaps faster in the future.

You are more than welcome to take the code in this vignette and adapt it to improve the speed. I provide a few different methods of accessing the data in the vignette. Perhaps a re-combination of them will provide fruitful.

Worst case scenario, 8 minutes isn't a terribly long time to wait for downloading data...

All the best,
-Robert
