### ISSUE TITLE
threshold calculation?

### ISSUE THREAD

**Issue by akashsinghraghuvanshi** [robwschlegel/heatwaveR#23]
does this code calculate threshold exceedance based on bootstrapping procedure defined by Zhang et al. (2005)? Hobday et al (2016) also mentioned the same as a caution.

**Comment by robwschlegel** [comment]
No it does not. After several years of active use of the Hobday definition the general consensus is that the bootstrapping procedure from Zhang et al. (2005) is not necessary. There are therefore no plans to implement this procedure in the R version of the Hobday code.
