### ISSUE TITLE
From gridded data to single point case study

### ISSUE THREAD

**Issue by LDoni** [robwschlegel/heatwaveR#24]
Hello,
Many thanks for develop your very useful package.
I would like to reproduce the subsequent  image from Hobday et al. (2016). 
![Immagine 2022-08-30 185911](https://user-images.githubusercontent.com/48062644/187496164-afefd264-daca-4c99-a4ea-22c02d6de382.png)
My study area is the  Great barrier Reef, Australia, and I'm interested to check the MHW of 2016 close to Mackay , visualizing data  from 2014 to 2017.
Following your [tutorial ](https://robwschlegel.github.io/heatwaveR/articles/OISST_preparation.html), I have downloaded the  Daily Global 5km Satellite Coral Bleaching Heat Stress Monitoring to plot gridded data about the Great barrier Reef, Australia , from 2014 to 2017. 

Do you know if when I visualize the data as you [suggest ](https://robwschlegel.github.io/heatwaveR/articles/OISST_preparation.html#visualise-data) in the  tutorial, the values are an average from 2014 to 2017?

How would you suggest me to pick the coordinates to do the case study? Is there a way to do the event_line plot directly from gridded data selecting specific coordinates? for test several locations close to Mackay area
All the best,
L

**Comment by ajsmit** [comment]
Good day,

Typically one would need 30 years’ worth of data, not four years as you suggest you have available. Heatwaves cannot be reliable calculated against such a short ‘climatology’ — a climatology according to the WMO has to be 30 years long (they discuss the considerations in selection time periods for climatology calculations).

The package can calculate a much shorter climatology, but then use the findings at your own risk. If you set the ‘climatologyPeriod’ argument in ‘ts2clim()' correctly, the climatology will be for that period. Not sure if this is what you ask in your question “the values are an average from 2014 to 2017?”?

The figure seen below in Alistair Hobday’s publication shows the MHW relative to the climatology chosen. Of course, his shows the MHW intensity on 28 Feb 2011 relative to a 30 year climatology. The lower figure shows the time series view of this, probably calculated for some smaller area of interest (at the dot in the top figure?).

To calculate the 'event_line()’ plot, you need to either extract a point (one grid point or pixel) or you can draw a bounding box around a rectangular area that captures several pixels, and then average them. Locate this bounding box over the area of interest.

Not sure if that answers your question, but feel free to discuss further if you need additional guidance.

AJS


---
AJ Smit

**Comment by LDoni** [comment]
Hello, 
thanks for the detailed answer!
understood:  30 years for the climatology .

“the values are an average from 2014 to 2017?”?
Nop, in your tutorial for download the gridded data, the last point is visualize the data:
`OISST_dat [%>%](https://magrittr.tidyverse.org/reference/pipe.html) 
  [filter](https://dplyr.tidyverse.org/reference/filter.html)(t == "2019-12-01") [%>%](https://magrittr.tidyverse.org/reference/pipe.html) 
  [ggplot](https://ggplot2.tidyverse.org/reference/ggplot.html)([aes](https://ggplot2.tidyverse.org/reference/aes.html)(x = lon, y = lat)) +
  [geom_tile](https://ggplot2.tidyverse.org/reference/geom_tile.html)([aes](https://ggplot2.tidyverse.org/reference/aes.html)(fill = temp)) +
  [scale_fill_viridis_c](https://ggplot2.tidyverse.org/reference/scale_viridis.html)() +
  [coord_quickmap](https://ggplot2.tidyverse.org/reference/coord_map.html)(expand = F) +
  [labs](https://ggplot2.tidyverse.org/reference/labs.html)(x = NULL, y = NULL, fill = "SST (°C)") +
  [theme](https://ggplot2.tidyverse.org/reference/theme.html)(legend.position = "bottom")`

I was wondering how the daily temperatures are finally represented for each pixel in this plot.
Is the resulting temperature of each plotted pixel (color) the average of all the daily temperatures of each pixel for the chosen period?

Yes exactly, they calculated the the time series for the dot in the top figure, 
"To calculate the 'event_line()’ plot, you need to either extract a point (one grid point or pixel) or you can draw a bounding box around a rectangular area that captures several pixels, and then average them. Locate this bounding box over the area of interest." okay got it!
Thanks,
L

**Comment by robwschlegel** [comment]
Hello Lapo,
It is unclear to me if you have any follow up questions in your post. If there are, may you please clarify? If not, can this issue be marked as closed?
All the best,
-Robert

**Comment by ajsmit** [comment]
This code...

OISST_dat %>%
  filter(t == "2019-12-01") %>%
  ggplot(aes(x = lon, y = lat)) +
  geom_tile(aes(fill = temp)) +
  scale_fill_viridis_c() +
  coord_quickmap(expand = F) +
  labs(x = NULL, y = NULL, fill = "SST (°C)") +
  theme(legend.position = "bottom")

…simply plots the temperature for the day 2019-12-01 — i.e the measured temperature for each pixel on that day. It simply visualises a day in the temperature time series for interest sake.

---
AJ Smit
