### ISSUE TITLE
Exact meaning of the "date_peak" metric 

### ISSUE THREAD

**Issue by DarrenLCY** [robwschlegel/heatwaveR#25]
Hi,

I hope you're doing well! 

I noticed something a bit strange with the "date_peak" metric when using detect_event(). In the figure below, 2 MHW events were detected, with the first lasting for 24 days and the second one lasting for 23 days:

![image](https://user-images.githubusercontent.com/67561176/220520633-cc06d378-0ef0-4873-9c86-37a22068be04.png)

The blue line is the 90th percentile threshold. I looked up the "date_peak" values for these 2 events, which I then show using the 2 vertical black dotted lines. However, the highest temperature of the first MHW event occurs at the vertical red dotted line, which brings me to my question: Is the "date_peak" metric the date at which the highest temperature is recorded during the event? According to the vignette, it is the "Date of event peak", which I think should be the case, correct?

Thank you very much,
Best regards,
Darren

**Comment by RQuilestinoOlario** [comment]
Hello Darren,

I think that the first vertical black line best reflects the 'date_peak' of your first MHW event. The 'date_peak' is the date when the highest **_intensity_**, not _temperature_, is attained by your MHW. Intensities are those values that exceed the 90th threshold. In your example, the first black line may not be the highest temperature during the first MHW but the difference between that day's SST and the threshold is greater than the day denoted by the red vertical line.

The second MHW shows that the highest temperature is also the point in your time series which has the highest 'distance' between the SST and your threshold, hence becoming the 'date_peak'.

I hope this helps and makes sense at the same time.

**Comment by robwschlegel** [comment]
Hello All,
@DarrenLCY the answer provided by @RQuilestinoOlario is exactly correct.

If you want to find the date of the highest temperature during a given event, this can be done by taking the daily results of the climatology dataframe produced by `detect_event()`. Filter by the event number (`event_no`) in qustion, and then take the date with the highest temperature.

All the best,
-Robert

**Comment by DarrenLCY** [comment]
Hi @RQuilestinoOlario and @robwschlegel, it does make sense. Thanks so much for the clarifications!
