### ISSUE TITLE
Error in griddap..... datasetx missing with no default

### ISSUE THREAD

**Issue by katsmimba** [robwschlegel/heatwaveR#26]
Hi @robwschlegel, I'm having some problems with running the MHW code the past few days. 

I realise NOAA have had some server issues at their end the past few weeks, but everything appears to be back up and running RE: OISST datasets. I'm now having trouble calling the data though. The info for the NOAA OISST data comes through absolutely fine, but when it comes to the data download I am getting an error message saying 'Error in griddap(x = "ncdcOisst21Agg_LonPM180", url = "https://coastwatch.pfeg.noaa.gov/erddap/",  :   argument "datasetx" is missing, with no default'.

Any idea's what I might be doing wrong? I have run this code hundreds of times without problems but just can't figure out where the issue is now!

Here is the code I am using: 

#The information for the NOAA OISST data
`rerddap::info(datasetid = "ncdcOisst21Agg_LonPM180", url = "https://coastwatch.pfeg.noaa.gov/erddap/")`

#This function downloads and prepares data based on user provided start and end dates
`OISST_sub_dl <- function(time_df){
  OISST_dat <- griddap(x = "ncdcOisst21Agg_LonPM180",
                       url = "https://coastwatch.pfeg.noaa.gov/erddap/",
                       time = c(time_df$start, time_df$end),
                       zlev = c(0, 0),
                       latitude = c(-34.01018, -34.01018),
                       longitude = c(151.23199, 151.23199),
                       fields = "sst")$data %>%
    mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z"))) %>%
    dplyr::rename(t = time, temp = sst) %>%
    select(lon, lat, t, temp) %>%
    na.omit()
}`

#Date download range by start and end dates per year
`dl_years <- data.frame(date_index = 1:5,
                       start = as.Date(c("1982-01-01", "1990-01-01",
                                         "1998-01-01", "2006-01-01", "2014-01-01")),
                       end = as.Date(c("1989-12-31", "1997-12-31",
                                       "2005-12-31", "2013-12-31", "2021-11-30")))
`
#Download all data with one nested request
`system.time(
  OISST_data_Sydney <- dl_years %>%
    group_by(date_index) %>%
    group_modify(~OISST_sub_dl(.x)) %>%
    ungroup() %>%
    select(lon, lat, t, temp)
) `

Thanks,
Katie

**Comment by RQuilestinoOlario** [comment]
Hello @katsmimba and good day

Have you tried the alternative of using:

griddap(**datasetx** = "ncdcOisst21Agg_LonPM180", url = "https://coastwatch.pfeg.noaa.gov/erddap/...

instead of the x argument?

**Comment by katsmimba** [comment]
Hi @RQuilestinoOlario,

Thanks for getting back to me so quickly - and what a simple fix! Thanks! 
The code now appears to be running fine again!

**Comment by katsmimba** [comment]
Hi again @RQuilestinoOlario, any other ideas? 
Using the argument datasetx, the code seemed to run, but it has been going for more than half an hour and has neither timed out nor completed!

**Comment by robwschlegel** [comment]
Indeed, the NOAA servers can be quite unresponsive at times. I hope this issue managed to resolve itself for you.
