### ISSUE TITLE
Event_line function isn't working

### ISSUE THREAD

**Issue by marinamega** [robwschlegel/heatwaveR#27]
At first, I wanna to thank you so much for this package and for the instructions. 
I'm tryng to use the event_line function to plot my climatology and the heatwave events, but the function is not working. When I use "Detect_geral2", which is the output from detect_event function (a 2 lenght list), appears "Error in match(x, table, nomatch = 0L) :  'match' requires vector arguments". I already tried to use only the climatology object from the detect_event list, but it didn't work either (appears: "Error in event_line(climatology_geral2, x = data, y = tmax, metric = duration,  :  Please ensure you are running this function on the output of 'heatwaveR::detect_event()' ").

Here is the function I'm using:
event_line(detect_geral2, x= data, y= tmax, spread = 150, metric = duration,
            start_date = "2019-06-16", end_date = "2022-09-08")

I tried to use Algiers data too, but it didn't work either. I really don't know how to fix it.

**Comment by robwschlegel** [comment]
Hello,
Without being able to see the base dataset you've used I can't say what exactly the problem may be.
Please try running the following code chunk to see if you receive errors:

```
# Load heatwaveR library
library(heatwaveR)

# Get climatology values
clim_Al <- ts2clm(heatwaveR::Algiers, x = t, y = tMax,
                  climatologyPeriod = c("1961-01-01", "1990-12-31"))

# Detect events in tMax
detect_Al <- detect_event(clim_Al, x = t, y = tMax)

# Plot an event
event_line(detect_Al, x = t, y = tMax, spread = 150, metric = duration,
           start_date = "2000-06-16", end_date = "2004-09-08")
```

This code chunk runs as expected, so I am assuming that the error in your code may be coming from your use of the `x` and `y` arguments in `event_line()`. Please ensure that the column names you are providing for the date (`x`) and temperature (`y`) columns match exactly yo your original data. It appears as though you are calling your x column `data` when you probably mean `date`. But again, without seeing the base data I can only guess.

All the best,
-Robert

**Comment by marinamega** [comment]
Hello Robert,
I tried to use your code, but it didn't work either. Again, appears the message: 
Error in match(x, table, nomatch = 0L) : 'match' requires vector arguments

All the best,
- Marina

**Comment by robwschlegel** [comment]
Hello Marina,
If the code chunk I posted doesn't run, then one or more packages have likely not been installed correctly on your computer. Please restart RStudio, update all of your packages, then try the code chunk again. If the error persists, please re-install  the **`data.table`** package specifically. Including all of it's dependencies:
```
install.packages('data.table', repos='http://cran.us.r-project.org', dependencies=TRUE)
```
If the issue persists try installing the most recent version of **`heatwaveR`**:
```
devtools::install_github("robwschlegel/heatwaveR")
```
If none of that works please let me know as the next step would be to completely uninstall then reinstall R+RStudio from your computer and install each package one at a time. Before doing so please post the output of `sessionInfo()` after running just the code chunk I posted above.
All the best,
-Robert
