### ISSUE TITLE
Change color of climatology in event_line(category = TRUE)

### ISSUE THREAD

**Issue by zechmeunier** [robwschlegel/heatwaveR#29]
Thank you for this amazing R package!

I'm hoping to display side-by-side panels in a single figure with **panel a** showing two years of marine heatwave data with `event_line(category = FALSE)` and **panel b** showing the peak category of the marine heatwave with `event_line(category = TRUE)`. I would like to use a single legend between the two graphs. However, the climatology line appears blue in **panel a** but dark gray in **panel b**. Is it possible to change the color scheme so that the climatology is always blue? It's pretty hard to distinguish dark gray from black in the legend of **panel b**.

I tried looking at the source code and just adding `+ geom_line(aes(y = seas, col = "blue"), size = 0.7)` after the call to event_line but R throws an error.

**Comment by RQuilestinoOlario** [comment]
Hello @zechmeunier 

Instead of using the event_line function then adding the `+ geom_line(aes(y = seas, col = "blue"), size = 0.7)`, you can use the custom visualization codes provided by Dr @robwschlegel [here](https://robwschlegel.github.io/heatwaveR/articles/event_categories.html), which are:

```
# Create category breaks and select slice of data.frame
clim_cat <- MHW$clim %>%
  dplyr::mutate(diff = thresh - seas,
                thresh_2x = thresh + diff,
                thresh_3x = thresh_2x + diff,
                thresh_4x = thresh_3x + diff) %>% 
  dplyr::slice(10580:10690)

# Set line colours
lineColCat <- c(
  "Temperature" = "black",
  "Climatology" = "gray20",
  "Threshold" = "darkgreen",
  "2x Threshold" = "darkgreen",
  "3x Threshold" = "darkgreen",
  "4x Threshold" = "darkgreen"
  )

# Set category fill colours
fillColCat <- c(
  "Moderate" = "#ffc866",
  "Strong" = "#ff6900",
  "Severe" = "#9e0000",
  "Extreme" = "#2d0000"
  )

ggplot(data = clim_cat, aes(x = t, y = temp)) +
  geom_flame(aes(y2 = thresh, fill = "Moderate")) +
  geom_flame(aes(y2 = thresh_2x, fill = "Strong")) +
  geom_flame(aes(y2 = thresh_3x, fill = "Severe")) +
  geom_flame(aes(y2 = thresh_4x, fill = "Extreme")) +
  geom_line(aes(y = thresh_2x, col = "2x Threshold"), size = 0.7, linetype = "dashed") +
  geom_line(aes(y = thresh_3x, col = "3x Threshold"), size = 0.7, linetype = "dotdash") +
  geom_line(aes(y = thresh_4x, col = "4x Threshold"), size = 0.7, linetype = "dotted") +
  geom_line(aes(y = seas, col = "Climatology"), size = 0.7) +
  geom_line(aes(y = thresh, col = "Threshold"), size = 0.7) +
  geom_line(aes(y = temp, col = "Temperature"), size = 0.6) +
  scale_colour_manual(name = NULL, values = lineColCat,
                      breaks = c("Temperature", "Climatology", "Threshold",
                                 "2x Threshold", "3x Threshold", "4x Threshold")) +
  scale_fill_manual(name = NULL, values = fillColCat, guide = FALSE) +
  scale_x_date(date_labels = "%b %Y") +
  guides(colour = guide_legend(override.aes = list(linetype = c("solid", "solid", "solid",
                                                                "dashed", "dotdash", "dotted"),
                                                   size = c(0.6, 0.7, 0.7, 0.7, 0.7, 0.7)))) +
  labs(y = "Temperature [°C]", x = NULL)
```

You may base your custom MHW plots using these codes and may this hopefully have helped you

**Comment by zechmeunier** [comment]
Thanks @RQuilestinoOlario !! That worked great! I still think the base code should have a blue line for climatology though.

**Comment by robwschlegel** [comment]
Hello @zechmeunier,
I'm happy to hear that you are enjoying using **`heatwaveR`**
Just for reference, the `event_line()` function was created to replicate the figures found in Hobday et al., 2016 & 2018, and to allow the user to quickly visualise their results. To create more detailed figures for publication it is advised to write one's own custom code, as @RQuilestinoOlario graciously demonstrated. 
It is for these reasons that the `event_line()` function has limited functionality. That and I don't think a blue line looks good with the category colours. Consider as well that this same colour scheme is used with marine cold-spells, which are blue.
All the best,
-Robert

**Comment by robwschlegel** [comment]
@zechmeunier I happen to be in the process of preparing **`heatwaveR`** for v1.0, and adding the ability to change the `event_line()` colours was a rather straight forward process, so I've added it to the current development version of the package (v0.4.6.9004). 

You can install the newest version here:
```
devtools::install_github("robwschlegel/heatwaveR")
```

See example here:

``` r
library(heatwaveR)
ts <- ts2clm(sst_WA, climatologyPeriod = c("1983-01-01", "2012-12-31"))
res <- detect_event(ts)
event_line(res, spread = 100, start_date = "2010-12-01",
           end_date = "2011-06-30", category = TRUE,
           line_colours = c("black", "blue", "red", "red", "red", "red"))
```

![](https://i.imgur.com/4YKBUtH.png)

<sup>Created on 2023-03-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
