### ISSUE TITLE
quotation marks are missed in "For a basic introduction to the detection and visualisation of events."

### ISSUE THREAD

**Issue by CongGao-CG** [robwschlegel/heatwaveR#31]
```
event_line(mhw, spread = 180, metric = intensity_max, 
           start_date = "1982-01-01", end_date = "2014-12-31")
lolli_plot(mhw, metric = intensity_max)


event_line(mcs, spread = 200, metric = intensity_cumulative,
           start_date = "1982-01-01", end_date = "2014-12-31")
lolli_plot(mcs, metric = intensity_cumulative, xaxis = event_no)
```

should be

```
event_line(mhw, spread = 180, metric = "intensity_max", 
           start_date = "1982-01-01", end_date = "2014-12-31")
lolli_plot(mhw, metric = "intensity_max")


event_line(mcs, spread = 200, metric = "intensity_cumulative",
           start_date = "1982-01-01", end_date = "2014-12-31")
lolli_plot(mcs, metric = "intensity_cumulative", xaxis = "event_no")
```

**Comment by robwschlegel** [comment]
Hello,
The documentation on the website is for the development version (or most recently released version, if it is an official release) of the heatwaveR package. From v4.6.9003 we had to update the functioning of the visualisation functions to keep pace with the backward dependency breaking changes that have been made in **`ggplot2`** and other **`tidyverse`** packages. This is why the quotation marks were removed. These functions now use the same column name evaluation methods found in **`tidyverse`** code.

We are currently working on rolling out v0.5.0, which will then codify all of these changes. And at some point within the next few months we will be rolling out v1.0.0, which will remove most dependencies from the package, and make way for the next large project we have planned in the MHW space.
All the best,
-Robert
