### ISSUE TITLE
error with select()

### ISSUE THREAD

**Issue by MauroMardones** [robwschlegel/heatwaveR#32]
Hi all,

I try to download some data buen appear this

```
system.time(
  OISST_data <- dl_years2 %>% 
     group_by(date_index) %>% 
     group_modify(~OISST_sub_dl(.x)) %>% 
     ungroup() %>% 
     dplyr::select(lon, lat, t, temp,ice)
) 
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'select': argument "datasetx" is missing, with no default

this is my `sessionInfo()`

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils    
[6] datasets  methods   base     

other attached packages:
 [1] sf_1.0-13         terra_1.6-47     
 [3] raster_3.6-11     sp_1.5-0         
 [5] patchwork_1.1.2   udunits2_0.13.2.1
 [7] heatwaveR_0.4.6   doParallel_1.0.17
 [9] iterators_1.0.14  foreach_1.5.2    
[11] tidync_0.3.0      lubridate_1.9.0  
[13] timechange_0.1.1  rerddap_1.0.3    
[15] forcats_0.5.2     stringr_1.5.0    
[17] dplyr_1.1.2       purrr_1.0.1      
[19] readr_2.1.3       tidyr_1.3.0      
[21] tibble_3.2.1      ggplot2_3.4.2    
[23] tidyverse_1.3.2  

Please helpmeet if can.

**Comment by robwschlegel** [comment]
Hello,
The maintainers of the `rerddap` package changed the argument within the `rerddap::griddap()` function from `x` to `datasetx`. I don't know why.
Please use the code from the most recent version of the vignette to fix the problem: https://robwschlegel.github.io/heatwaveR/articles/OISST_preparation.html

**Comment by MauroMardones** [comment]
Thanks

Solve it.

Now another bug.

When run example, I get this:

```
base::system.time(
+   OISST_data <- dl_years %>% 
+     dplyr::group_by(date_index) %>% 
+     dplyr::group_modify(~OISST_sub_dl(.x)) %>% 
+     dplyr::ungroup() %>% 
+     dplyr::select(lon, lat, t, temp)
+ ) 
```

[1] "time must be given as character strings"
Warning: NAs introduced by coercionError in print.default("you are passing ", paste0(class(dimargs$time))) : 
  invalid printing digits -2147483648
Timing stopped at: 0.16 0.015 1.933

you know why?

**Comment by robwschlegel** [comment]
It appears that the time values you are giving to the function are not in the correct format. Without seeing the code you are using I cannot be certain.

**Comment by robwschlegel** [comment]
Specifically, the values you are putting into `dl_years`

**Comment by MauroMardones** [comment]
HI Rob
sorry, this is my code:


```
OISST_sub_dl <- function(time_df){
  OISST_dat <- rerddap::griddap(datasetx = "ncdcOisst21Agg_LonPM180",
                                url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
                                time = c(time_df$start, time_df$end), 
                                zlev = c(0, 0),
                                latitude = c(-76, -55),
                                longitude = c(-90, -30),
                                fields = c("sst","ice"))$data %>% 
    dplyr::mutate(time = base::as.Date(stringr::str_remove(time, "T12:00:00Z"))) %>% 
    dplyr::rename(t = time, temp = sst, sic=ice,lon = longitude, lat = latitude) %>% 
    dplyr::select(lon, lat, t, temp, sic) %>% 
    stats::na.omit()
}



dl_years <- data.frame(date_index = 1:8,
                        start = as.Date(c("1985-01-01","1990-01-01",
                                          "1995-01-01", "2000-01-01", "2006-01-01", 
                                          "2013-01-01","2019-01-01","2021-01-01")),
                        
                        end = as.Date(c("1989-12-31","1994-12-31",
                                        "1999-12-31", "2005-12-31", "2012-12-31", 
                                        "2018-12-31","2020-12-31","2022-12-31")))

```

**Comment by robwschlegel** [comment]
This may be the issue:
`fields = c("sst","ice"))$data`
Try running the code and only download "sst
`fields = "sst")$data`
I've not tested the code if it can download and process multiple fields at once.
If you need it to do so, you will need to debug the code yourself.

**Comment by robwschlegel** [comment]
I looked into this more closely now.

This code runs:
`OISST_sub_dl <- function(time_df){
  OISST_dat <- rerddap::griddap(datasetx = "ncdcOisst21Agg_LonPM180",
                                url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
                                time = c(time_df$start, time_df$end), 
                                zlev = c(0, 0),
                                latitude = c(88, 89),
                                longitude = c(15, 16),
                                fields = c("sst", "ice"))$data %>% 
    dplyr::mutate(time = base::as.Date(stringr::str_remove(time, "T12:00:00Z"))) %>%
    dplyr::rename(t = time, temp = sst, lon = longitude, lat = latitude) %>%
    dplyr::select(lon, lat, t, temp, ice) %>%
    stats::na.omit()
}`

# One set
`time_df <- data.frame(start = as.Date("1982-01-01"),
                      end = as.Date("1982-12-31"))
OISST_data <- OISST_sub_dl(time_df)`

It appears that if there are no ice data in the selected lon/lat range it can cause errors. This is unexpected behaviour. And I am not the maintainer of the rerddap package. So I can't provide further assistance on why their source code does what it does.
