### ISSUE TITLE
Help with downloading and preparing OISST data vignette

### ISSUE THREAD

**Issue by katsmimba** [robwschlegel/heatwaveR#34]
Hi, I have used the heatwaveR package a lot the past few years with no problems. I have been trying to use it for the past few days after not opening it for several months and when I get to the final section of the 'downloading and preparing' code I'm hitting an error. 

This is the code I'm running:
# The packages we will use
library(dplyr) # A staple for modern data management in R
library(lubridate) # Useful functions for dealing with dates
library(ggplot2) # The preferred library for data visualisation
library(tidync) # For easily dealing with NetCDF data
library(rerddap) # For easily downloading subsets of data
library(doParallel) # For parallel processing
library(heatwaveR)

# The information for the NOAA OISST data
rerddap::info(datasetid = "ncdcOisst21Agg_LonPM180", url = "[https://coastwatch.pfeg.noaa.gov/erddap/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoastwatch.pfeg.noaa.gov%2Ferddap%2F&data=05%7C01%7Ckatsmi%40mba.ac.uk%7C93380ceb8214415ebdcb08dbf66d18d4%7C8f72cb4bfef34e28b2db8876027b0b99%7C1%7C0%7C638374720743517672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yXTx4uighrEZeAnpls5hS0m8YbO5gsr3mS85Wvy%2B8%2BE%3D&reserved=0)")

# This function downloads and prepares data based on user provided start and end dates
OISST_sub_dl <- function(time_df){
  OISST_dat <- rerddap::griddap(datasetx = "ncdcOisst21Agg_LonPM180", 
                       url = "[https://coastwatch.pfeg.noaa.gov/erddap/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoastwatch.pfeg.noaa.gov%2Ferddap%2F&data=05%7C01%7Ckatsmi%40mba.ac.uk%7C93380ceb8214415ebdcb08dbf66d18d4%7C8f72cb4bfef34e28b2db8876027b0b99%7C1%7C0%7C638374720743517672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yXTx4uighrEZeAnpls5hS0m8YbO5gsr3mS85Wvy%2B8%2BE%3D&reserved=0)", 
                       time = c(time_df$start, time_df$end), 
                       zlev = c(0, 0),
                       latitude = c(42, 42),
                       longitude = c(4, 4),
                       fields = "sst")$data %>% 
    mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z"))) %>% 
    dplyr::rename(t = time, temp = sst) %>% 
    select(lon, lat, t, temp) %>% 
    na.omit()
}

# Date download range by start and end dates per year
dl_years <- data.frame(date_index = 1:5,
                       start = as.Date(c("1982-01-01", "1990-01-01", 
                                         "1998-01-01", "2006-01-01", "2014-01-01")),
                       end = as.Date(c("1989-12-31", "1997-12-31", 
                                       "2005-12-31", "2013-12-31", "2019-12-31")))

# Download all of the data with one nested request
# The time this takes will vary greatly based on connection speed
base::system.time(
  OISST_data <- dl_years %>% 
    dplyr::group_by(date_index) %>% 
    dplyr::group_modify(~OISST_sub_dl(.x)) %>% 
    dplyr::ungroup() %>% 
    dplyr::select(lon, lat, t, temp),
  gcFirst = FALSE
) # 518 seconds, ~100 seconds per batch

When I get to this final section I get the following error:
[1] "time must be given as character strings"
Error in print.default("you are passing ", paste0(class(dimargs$time))) : 
  invalid printing digits -2147483648
In addition: Warning message:
In print.default("you are passing ", paste0(class(dimargs$time))) :

 Error in print.default("you are passing ", paste0(class(dimargs$time))) : 
invalid printing digits -2147483648 Timing stopped at: 0.4 0.04 2.69

I have tried running it on multiple computers, updating R, updating all the packages, but am still having no luck. Any ideas?

**Comment by robwschlegel** [comment]
Hello,
Someone else recently sent a similar error.
I assume that one of the packages that downloads NOAA data has changed the way it works. They do that from time to time.
None of that code has anything to do with the heatwaveR package and I do not maintain it, so I can't comment on what the issue may be.
I would recommend going through the code line by line to see where the error occurs. My guess is that it is `rerddap::griddap()`. If you are able to find the issue please post it here so other people may find it.
When I am able to find time to do so I will go through the code.
All the best,
-Robert

**Comment by katsmimba** [comment]
Thanks Robert-I will see what I can find out!
I notice time comes through from the dataset as "time: (1981-09-01T12:00:00Z, 2023-11-20T12:00:00Z)". 
I'm not sure if the date was always incorporated or if this might be a reason. 
Best, 
Katie

**Comment by robwschlegel** [comment]
Hello,
For whatever their reasons may be, the managers of the __`rerddap`__ package changed the query process to require the dates as character values, rather than dates. Curious choice. Regardless, the code will run if you change this one bit.

```
# Date download range by start and end dates per year
dl_years <- data.frame(date_index = 1:5,
                       start = c("1982-01-01", "1990-01-01", 
                                 "1998-01-01", "2006-01-01", "2014-01-01"),
                       end = c("1989-12-31", "1997-12-31", 
                               "2005-12-31", "2013-12-31", "2019-12-31"))
```
I've updated this online as well.
All the best,
-Robert

**Comment by robwschlegel** [comment]
Hello,
For whatever their reasons may be, the managers of the __`rerddap`__ package changed the query process to require the dates as character values, rather than dates. Curious choice. Regardless, the code will run if you change this one bit.

```
# Date download range by start and end dates per year
dl_years <- data.frame(date_index = 1:5,
                       start = c("1982-01-01", "1990-01-01", 
                                 "1998-01-01", "2006-01-01", "2014-01-01"),
                       end = c("1989-12-31", "1997-12-31", 
                               "2005-12-31", "2013-12-31", "2019-12-31"))
```
I've updated this online as well.
All the best,
-Robert

**Comment by katsmimba** [comment]
Thanks-interestingly on one of my computers I have a different error message. The old code runs fine with the edit of replacing ‘lat’ with ‘latitude’ and ‘lon’ with ‘longitude’. I’m not sure why! That computer is on a slightly older version of R (4.2.2 rather than 4.2.3).

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
