### ISSUE TITLE
Change to code for pulling SST data from rerddap package

### ISSUE THREAD

**Issue by katsmimba** [robwschlegel/heatwaveR#35]
Hi, this is a 'solve' more than an issue. 
There were recently problems with downloading SST data using the rerddap package because of a change in the query process to require the dates as character values, rather than dates. 

In addition to this, they also appear to have updated column headings to read 'latitude' and 'longitude' instead of 'lat' and 'lon'. 

I have got around this by updating this piece of code; specifically the dplyr::rename section: 
OISST_sub_dl <- function(time_df){
  OISST_dat <- rerddap::griddap(datasetx = "ncdcOisst21Agg_LonPM180", 
                                url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
                                time = c(time_df$start, time_df$end), 
                                zlev = c(0, 0),
                                latitude = c(50.230981, 50.230981),
                                longitude = c(-3.928535, -3.928535),
                                fields = "sst")$data %>% 
    mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z"))) %>% 
    dplyr::rename(t = time, temp = sst, lon = longitude, lat = latitude) %>% 
    select(lon, lat, t, temp) %>% 
    na.omit()

Hope this helps!

**Comment by robwschlegel** [comment]
Wonderful :)
