### ISSUE TITLE
Why event is true when both threshCriterion and durationCriterion are false

### ISSUE THREAD

**Issue by CongGao-CG** [robwschlegel/heatwaveR#38]
```
library(dplyr)
library(ggplot2)
library(heatwaveR)

# Detect the events in a time series
ts <- ts2clm(sst_WA, climatologyPeriod = c("1982-01-01", "2011-12-31"))
mhw <- detect_event(ts)

 mhw$climatology |> filter(event == TRUE, threshCriterion == FALSE)
```
A tibble: 11 × 9
     doy t           temp  seas thresh threshCriterion durationCriterion event event_no
   <int> <date>     <dbl> <dbl>  <dbl> <lgl>           <lgl>             <lgl>    <int>
 1   251 1989-09-07  20.8  19.8   20.8 FALSE           FALSE             TRUE        18
 2   252 1989-09-08  20.7  19.8   20.8 FALSE           FALSE             TRUE        18
 3    12 1997-01-12  23.1  21.8   23.1 FALSE           FALSE             TRUE        26
 4   247 1998-09-03  20.5  19.9   20.9 FALSE           FALSE             TRUE        28
 5   248 1998-09-04  20.4  19.9   20.8 FALSE           FALSE             TRUE        28
 6   122 2000-05-01  24.5  23.3   24.6 FALSE           FALSE             TRUE        31
 7   123 2000-05-02  24.4  23.3   24.6 FALSE           FALSE             TRUE        31
 8    91 2008-03-31  24.1  23.3   24.3 FALSE           FALSE             TRUE        41
 9   319 2010-11-14  21.4  20.4   21.4 FALSE           FALSE             TRUE        50
10   342 2011-12-07  22.1  21.0   22.2 FALSE           FALSE             TRUE        58
11   343 2011-12-08  22.0  21.0   22.2 FALSE           FALSE             TRUE        58

**Comment by robwschlegel** [comment]
This is because the max gap between events is set as 2 days by default. Therefore, even if temperatures go below the threshold for one or two consecutive days the event flag will still be TRUE.
To change this behaviour set `maxGap = 0`
