### ISSUE TITLE
depricated ggplot2 call 

### ISSUE THREAD

**Issue by hermandemunnik** [robwschlegel/heatwaveR#39]
Hi, 

Very minor issue, but the event_line() function uses deprecated ggplot syntax. 

Best wishes,
Herman 

![image](https://github.com/user-attachments/assets/5dfad15b-b360-4b10-a764-bc65f64415e0)

**Comment by hermandemunnik** [comment]
Noticed it's already solved in the development version, cheers

**Comment by robwschlegel** [comment]
There was another reverse dependency breaking issues via ggplot2 which has just been fixed as well.
